### ISSUE TITLE
Only first 180 games are processed?

### ISSUE THREAD

**Issue by Jonathan003** [Dedekind125/chess-claim-tool#9]
I have a pgn file with 263 games with 3 fold repetitions find by pgn-extract
with this command
`pgn-extract --repetition tocheck.pgn -nothers.pgn > repetition.pgn`

If I run Chess Claim Tool, only 180 Three-fold repetitions are find.
Than I get this Scan Waiting message.

![image](https://github.com/dedekind125/chess-claim-tool/assets/40061628/31216975-442b-4110-9ac3-a68156728c53)

Ore there are only 180 Thee-fold repetitions find with Chess Claim Tool or it just quits after 180 three-fold repetitions are find?

**Comment by dedekind125** [comment]
Hey @Jonathan003, can you also provide the ` tocheck.pgn` file is same shape or form?

Note: I do not have any plans for developing this version of the tool further, but I want to know why it failed to recognized all 263!

**Comment by Jonathan003** [comment]
I don't have the exact files anymore.
[tocheck.zip](https://github.com/dedekind125/chess-claim-tool/files/14009964/tocheck.zip)
[repetition.zip](https://github.com/dedekind125/chess-claim-tool/files/14009969/repetition.zip)

If I run the Chess Claim Tool with the repetitions.pgn file it only processes 197 games.
And there are 281 games (all with threefold "ore more-fold", repetitions, find with pgn-extract" in the repetitions.pgn file.

**Comment by dedekind125** [comment]
Thanks for providing the files! 

The issue is that in the files that you are scanning there are games played by the same set of players. The tool always display the latest claim and it overwrites/deletes the old entries with the same set of players. So, even though the tool finds all the 281 games, 2 or more games of the same set of players are counted as 1.

This is somewhat intended considering the motivation of the tool, meant to be used as a live assistant to the arbiter for FIDE official tournaments. For this use-case scenario, only the latest claim of a 3-Fold repetition/50 Moves rule matter; all the previous claims do not hold any value to the arbiter. Honestly, I never considered to have 2 games by the same players in one round, but it kinda falls to the same category.

**Comment by Jonathan003** [comment]
I have modified the tool, to truncate games one ply before a threefold repetition, and to set the result to draw in the output.
I did it with a lot of trial and error with Microsoft Copilot. (I have no programming knowledge).

If you want to try this script just drag a pgn (in the same folder of the scipt), to the script to run it.

It looks like this script works correct also if the input databases have the same set of players.

The script is very slow, do you know how it can made much faster?
Ore maybe to create a complete new scipt that is much faster?
I have tried to run the scipt with pypy but that isn't faster.

Here is the script truncate_one_ply_before_threefold_repetition.py:

`
import chess.pgn
import os
import sys

def truncate_threefold_repetition(pgn_filepath):
    truncated_games = []
    with open(pgn_filepath) as pgn_file:
        while True:
            game = chess.pgn.read_game(pgn_file)
            if game is None:
                break  # end of file
            board = game.board()
            game_states = {board.board_fen(): 1}
            last_move = None
            for move in game.mainline_moves():
                if game_states[board.board_fen()] >= 3:
                    break
                last_move = move
                board.push(move)
                fen = board.board_fen()
                game_states[fen] = game_states.get(fen, 0) + 1
            if last_move is not None:
                board.pop()  # Remove the last move
            truncated_game = chess.pgn.Game.from_board(board)
            truncated_game.headers = game.headers  # Copy headers from original game
            truncated_game.headers["Result"] = "1/2-1/2"  # Set result to draw
            exporter = chess.pgn.StringExporter(headers=True, variations=True, comments=True)
            truncated_game.accept(exporter)
            truncated_games.append(str(exporter))
    return truncated_games

def write_truncated_games(truncated_games, output_filepath):
    with open(output_filepath, 'w') as output_file:
        for game in truncated_games:
            output_file.write(game + '\n\n')

def main():
    if len(sys.argv) != 2:
        print("Usage: truncate_one_ply_before_threefold-repetition.py path_to_your_pgn_file.pgn")
        return
    pgn_filepath = sys.argv[1]
    if not os.path.isfile(pgn_filepath):
        print("Error: The specified file does not exist.")
        return
    output_folder = 'output'
    os.makedirs(output_folder, exist_ok=True)
    output_filename = os.path.splitext(os.path.basename(pgn_filepath))[0] + '.pgn'
    output_filepath = os.path.join(output_folder, output_filename)
    truncated_games = truncate_threefold_repetition(pgn_filepath)
    write_truncated_games(truncated_games, output_filepath)

if __name__ == '__main__':
    main()
`
